export const SHEET_NAMES = {
  employees: 'Employees',
  schedules: 'Schedule',
  attendance: 'Attendance',
  payroll: 'Payroll',
  settings: 'Settings',
  inventory: 'Inventory',
  purchaseOrders: 'PurchaseOrders',
  sales: 'Sales',
} as const;

export const HEADERS = {
  employees: [
    'id',
    'name',
    'position',
    'hourly_wage',
    'phone',
    'hire_date',
    'status',
    'updated_at',
  ],
  schedules: [
    'id',
    'year',
    'month',
    'day',
    'row_id',
    'name',
    'start_time',
    'end_time',
    'duration',
    'updated_at',
  ],
  attendance: [
    'id',
    'employee_id',
    'employee_name',
    'date',
    'shift_id',
    'scheduled_start',
    'scheduled_end',
    'actual_start',
    'actual_end',
    'status',
    'modification_reason',
    'is_manually_edited',
    'updated_at',
  ],
  payroll: [
    'employee_id',
    'period',
    'period_key',
    'bonus',
    'meal_allowance',
    'transportation_allowance',
    'advance_deduction',
    'penalty_deduction',
    'custom_label',
    'custom_amount',
    'note',
    'updated_at',
  ],
  settings: ['key', 'value', 'updated_at'],
  inventory: [
    'id',
    'name',
    'current_stock',
    'min_stock',
    'expiry_date',
    'updated_at',
  ],
  purchaseOrders: [
    'id',
    'product_name',
    'quantity',
    'status',
    'scheduled_date',
    'note',
    'updated_at',
  ],
  sales: ['id', 'date', 'amount', 'note', 'updated_at'],
} as const;
